version: '3'

services:

  analyzer-earmo-api:
    container_name: analyzer-earmo-api
    image: greenstamp/analyzer-earmo-api
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 4003:3000
    environment:
      DELIVER_RESULTS_ENDPOINT: 'http://51.210.255.156:3000/api/result'
      EARMO_HOME: '/data/'
      UPLOADS_HOME: ${UPLOADS_HOME}
    volumes:
      - '/data/greenstamp/analyzer-earmo-api:/data'